<?php

/*
|--------------------------------------------------------------------------
| Reviewed common-food vocabulary
|--------------------------------------------------------------------------
|
| These rows do not invent nutrition data. The curation command selects a
| suitable imported generic record, copies its nutrition values into a stable
| canonical food, and records the source food in nutrition_source_food_id.
|
*/

return [
    ['key' => 'egg', 'en' => 'Egg', 'ro' => 'Ou', 'ro_aliases' => ['Ouă', 'Oua'], 'candidates' => ['Egg, whole, raw', 'Whole egg', 'Egg']],
    ['key' => 'rice', 'en' => 'Rice', 'ro' => 'Orez', 'candidates' => ['Rice, white, cooked, no added fat', 'Rice, white, cooked, as ingredient', 'White rice, cooked']],
    ['key' => 'grapes', 'en' => 'Grapes', 'ro' => 'Struguri', 'candidates' => ['Grapes, raw', 'Grape']],
    ['key' => 'bread', 'en' => 'Bread', 'ro' => 'Pâine', 'candidates' => ['Bread, white', 'Bread']],
    ['key' => 'whole_milk', 'en' => 'Whole milk', 'ro' => 'Lapte integral', 'candidates' => ['Milk, whole', 'Whole milk']],
    ['key' => 'skimmed_milk', 'en' => 'Skimmed milk', 'ro' => 'Lapte degresat', 'candidates' => ['Milk, nonfat', 'Milk, skimmed', 'Skimmed milk']],
    ['key' => 'cheese', 'en' => 'Cheese', 'ro' => 'Brânză', 'candidates' => ['Cheese, cheddar', 'Cheese']],
    ['key' => 'cottage_cheese', 'en' => 'Cottage cheese', 'ro' => 'Brânză de vaci', 'candidates' => ['Cheese, cottage', 'Cottage cheese']],
    ['key' => 'feta', 'en' => 'Feta', 'ro' => 'Brânză feta', 'candidates' => ['Cheese, feta', 'Feta']],
    ['key' => 'mozzarella', 'en' => 'Mozzarella', 'ro' => 'Mozzarella', 'candidates' => ['Cheese, mozzarella', 'Mozzarella']],
    ['key' => 'yogurt', 'en' => 'Yogurt', 'ro' => 'Iaurt', 'candidates' => ['Yogurt, plain, whole milk', 'Yoghurt, plain', 'Yogurt, plain']],
    ['key' => 'greek_yogurt', 'en' => 'Greek yogurt', 'ro' => 'Iaurt grecesc', 'candidates' => ['Yogurt, Greek, plain, whole milk', 'Yogurt, Greek style, plain']],
    ['key' => 'butter', 'en' => 'Butter', 'ro' => 'Unt', 'candidates' => ['Butter, salted', 'Butter']],
    ['key' => 'sour_cream', 'en' => 'Sour cream', 'ro' => 'Smântână', 'candidates' => ['Sour cream, regular', 'Sour cream, 10-12% fat']],
    ['key' => 'chicken_breast', 'en' => 'Chicken breast', 'ro' => 'Piept de pui', 'candidates' => ['Chicken, broiler, breast, meat, roasted', 'Chicken breast, stewed, skin not eaten']],
    ['key' => 'turkey_breast', 'en' => 'Turkey breast', 'ro' => 'Piept de curcan', 'candidates' => ['Turkey, breast, cooked', 'Turkey breast']],
    ['key' => 'beef', 'en' => 'Beef', 'ro' => 'Carne de vită', 'candidates' => ['Beef, NFS', 'Beef, roast']],
    ['key' => 'pork', 'en' => 'Pork', 'ro' => 'Carne de porc', 'candidates' => ['Pork, NFS', 'Pork, roast']],
    ['key' => 'bacon', 'en' => 'Bacon', 'ro' => 'Bacon', 'candidates' => ['Bacon, cooked', 'Bacon']],
    ['key' => 'ham', 'en' => 'Ham', 'ro' => 'Șuncă', 'candidates' => ['Ham, cooked', 'Ham']],
    ['key' => 'sausage', 'en' => 'Sausage', 'ro' => 'Cârnați', 'candidates' => ['Sausage, NFS', 'Sausages, beef, grilled']],
    ['key' => 'salmon', 'en' => 'Salmon', 'ro' => 'Somon', 'candidates' => ['Salmon, wild, baked', 'Salmon, wild, grilled']],
    ['key' => 'tuna', 'en' => 'Tuna', 'ro' => 'Ton', 'candidates' => ['Tuna, flesh only, raw', 'Tuna, canned in water']],
    ['key' => 'cod', 'en' => 'Cod', 'ro' => 'Cod', 'candidates' => ['Cod, flesh only, raw', 'Cod, cooked']],
    ['key' => 'mackerel', 'en' => 'Mackerel', 'ro' => 'Macrou', 'candidates' => ['Mackerel, grilled, no added fat', 'Mackerel, steamed, no added fat', 'Mackerel, raw']],
    ['key' => 'shrimp', 'en' => 'Shrimp', 'ro' => 'Creveți', 'candidates' => ['Shrimps, boiled', 'Prawns, king, purchased cooked', 'Shrimp, grilled']],
    ['key' => 'potato', 'en' => 'Potato', 'ro' => 'Cartof', 'candidates' => ['Potato, boiled, flesh and skin', 'Potato, boiled without skin, flesh', 'Potatoes, boiled']],
    ['key' => 'sweet_potato', 'en' => 'Sweet potato', 'ro' => 'Cartof dulce', 'candidates' => ['Sweet potato, cooked', 'Sweet potato']],
    ['key' => 'tomato', 'en' => 'Tomato', 'ro' => 'Roșie', 'ro_aliases' => ['Tomate'], 'candidates' => ['Tomato, raw', 'Tomatoes, raw', 'Tomato']],
    ['key' => 'onion', 'en' => 'Onion', 'ro' => 'Ceapă', 'candidates' => ['Onion, raw', 'Onions, raw', 'Onion']],
    ['key' => 'garlic', 'en' => 'Garlic', 'ro' => 'Usturoi', 'candidates' => ['Garlic, raw', 'Garlic']],
    ['key' => 'carrot', 'en' => 'Carrot', 'ro' => 'Morcov', 'candidates' => ['Carrot, raw', 'Carrots, raw', 'Carrot']],
    ['key' => 'cucumber', 'en' => 'Cucumber', 'ro' => 'Castravete', 'candidates' => ['Cucumber, raw', 'Cucumber']],
    ['key' => 'bell_pepper', 'en' => 'Bell pepper', 'ro' => 'Ardei gras', 'candidates' => ['Capsicum, red, fresh, raw', 'Capsicum, green, fresh, raw', 'Peppers, raw, NFS']],
    ['key' => 'broccoli', 'en' => 'Broccoli', 'ro' => 'Broccoli', 'candidates' => ['Broccoli, raw', 'Broccoli']],
    ['key' => 'cauliflower', 'en' => 'Cauliflower', 'ro' => 'Conopidă', 'candidates' => ['Cauliflower, raw', 'Cauliflower']],
    ['key' => 'spinach', 'en' => 'Spinach', 'ro' => 'Spanac', 'candidates' => ['Spinach, raw', 'Spinach']],
    ['key' => 'lettuce', 'en' => 'Lettuce', 'ro' => 'Salată verde', 'candidates' => ['Lettuce, raw', 'Lettuce']],
    ['key' => 'cabbage', 'en' => 'Cabbage', 'ro' => 'Varză', 'candidates' => ['Cabbage, raw', 'Cabbage']],
    ['key' => 'mushrooms', 'en' => 'Mushrooms', 'ro' => 'Ciuperci', 'candidates' => ['Mushrooms, raw', 'Mushroom']],
    ['key' => 'zucchini', 'en' => 'Zucchini', 'ro' => 'Dovlecel', 'candidates' => ['Zucchini, raw', 'Courgette, raw', 'Zucchini']],
    ['key' => 'eggplant', 'en' => 'Eggplant', 'ro' => 'Vânătă', 'candidates' => ['Eggplant, raw', 'Aubergine, raw', 'Eggplant']],
    ['key' => 'beans', 'en' => 'Beans', 'ro' => 'Fasole', 'candidates' => ['Beans, NFS', 'Beans, cooked']],
    ['key' => 'chickpeas', 'en' => 'Chickpeas', 'ro' => 'Năut', 'candidates' => ['Chickpeas, from dried, no added fat', 'Chickpea, dried, boiled, drained']],
    ['key' => 'lentils', 'en' => 'Lentils', 'ro' => 'Linte', 'candidates' => ['Lentils, red, cooked', 'Lentils, NFS']],
    ['key' => 'peas', 'en' => 'Peas', 'ro' => 'Mazăre', 'candidates' => ['Peas, green, cooked', 'Peas']],
    ['key' => 'corn', 'en' => 'Corn', 'ro' => 'Porumb', 'candidates' => ['Corn, raw', 'Corn, sweet, cooked', 'Sweetcorn, cooked']],
    ['key' => 'oats', 'en' => 'Oats', 'ro' => 'Ovăz', 'ro_aliases' => ['Fulgi de ovăz'], 'candidates' => ['Oats, rolled', 'Oat flakes', 'Oats']],
    ['key' => 'pasta', 'en' => 'Pasta', 'ro' => 'Paste', 'candidates' => ['Pasta, cooked', 'Macaroni, cooked', 'Pasta']],
    ['key' => 'flour', 'en' => 'Flour', 'ro' => 'Făină', 'candidates' => ['Flour, wheat', 'Wheat flour', 'Flour']],
    ['key' => 'sugar', 'en' => 'Sugar', 'ro' => 'Zahăr', 'candidates' => ['Sugar', 'Sugars, granulated']],
    ['key' => 'honey', 'en' => 'Honey', 'ro' => 'Miere', 'candidates' => ['Honey']],
    ['key' => 'olive_oil', 'en' => 'Olive oil', 'ro' => 'Ulei de măsline', 'candidates' => ['Oil, olive', 'Olive oil']],
    ['key' => 'sunflower_oil', 'en' => 'Sunflower oil', 'ro' => 'Ulei de floarea-soarelui', 'candidates' => ['Oil, sunflower', 'Sunflower oil']],
    ['key' => 'banana', 'en' => 'Banana', 'ro' => 'Banană', 'candidates' => ['Banana, raw', 'Banana']],
    ['key' => 'apple', 'en' => 'Apple', 'ro' => 'Măr', 'candidates' => ['Apple, raw', 'Apples, raw', 'Apple']],
    ['key' => 'orange', 'en' => 'Orange', 'ro' => 'Portocală', 'candidates' => ['Orange, raw', 'Oranges, raw', 'Orange']],
    ['key' => 'pear', 'en' => 'Pear', 'ro' => 'Pară', 'candidates' => ['Pear, raw', 'Pears, raw', 'Pear']],
    ['key' => 'peach', 'en' => 'Peach', 'ro' => 'Piersică', 'candidates' => ['Peach, raw', 'Peaches, raw', 'Peach']],
    ['key' => 'plum', 'en' => 'Plum', 'ro' => 'Prună', 'candidates' => ['Plum, raw', 'Plums, raw', 'Plum']],
    ['key' => 'strawberries', 'en' => 'Strawberries', 'ro' => 'Căpșuni', 'candidates' => ['Strawberries, raw', 'Strawberry']],
    ['key' => 'blueberries', 'en' => 'Blueberries', 'ro' => 'Afine', 'candidates' => ['Blueberries, raw', 'Blueberry']],
    ['key' => 'raspberries', 'en' => 'Raspberries', 'ro' => 'Zmeură', 'candidates' => ['Raspberries, raw', 'Raspberry']],
    ['key' => 'watermelon', 'en' => 'Watermelon', 'ro' => 'Pepene verde', 'candidates' => ['Watermelon, raw', 'Watermelon']],
    ['key' => 'melon', 'en' => 'Melon', 'ro' => 'Pepene galben', 'candidates' => ['Melon, cantaloupe, raw', 'Melon, honeydew, raw']],
    ['key' => 'pineapple', 'en' => 'Pineapple', 'ro' => 'Ananas', 'candidates' => ['Pineapple, raw', 'Pineapple']],
    ['key' => 'kiwi', 'en' => 'Kiwi', 'ro' => 'Kiwi', 'candidates' => ['Kiwi fruit, raw', 'Kiwifruit, green, raw', 'Kiwi fruit, without skin']],
    ['key' => 'avocado', 'en' => 'Avocado', 'ro' => 'Avocado', 'candidates' => ['Avocado, raw', 'Avocado']],
    ['key' => 'almonds', 'en' => 'Almonds', 'ro' => 'Migdale', 'candidates' => ['Almonds, raw', 'Almonds']],
    ['key' => 'walnuts', 'en' => 'Walnuts', 'ro' => 'Nuci', 'candidates' => ['Walnuts, kernel only', 'Walnuts, excluding honey roasted']],
    ['key' => 'peanuts', 'en' => 'Peanuts', 'ro' => 'Arahide', 'candidates' => ['Peanuts, raw', 'Peanuts']],
    ['key' => 'cashews', 'en' => 'Cashews', 'ro' => 'Caju', 'candidates' => ['Cashews, raw', 'Cashew nuts']],
    ['key' => 'pumpkin_seeds', 'en' => 'Pumpkin seeds', 'ro' => 'Semințe de dovleac', 'candidates' => ['Seeds, pumpkin', 'Pumpkin seeds']],
    ['key' => 'sunflower_seeds', 'en' => 'Sunflower seeds', 'ro' => 'Semințe de floarea-soarelui', 'candidates' => ['Seeds, sunflower', 'Sunflower seeds']],
    ['key' => 'tofu', 'en' => 'Tofu', 'ro' => 'Tofu', 'candidates' => ['Tofu, firm', 'Tofu']],
    ['key' => 'mayonnaise', 'en' => 'Mayonnaise', 'ro' => 'Maioneză', 'candidates' => ['Mayonnaise, regular', 'Mayonnaise']],
    ['key' => 'ketchup', 'en' => 'Ketchup', 'ro' => 'Ketchup', 'candidates' => ['Ketchup', 'Tomato ketchup']],
    ['key' => 'water', 'en' => 'Water', 'ro' => 'Apă', 'candidates' => ['Water, tap', 'Water']],
    ['key' => 'coffee', 'en' => 'Coffee', 'ro' => 'Cafea', 'candidates' => ['Coffee, brewed', 'Coffee']],
    ['key' => 'tea', 'en' => 'Tea', 'ro' => 'Ceai', 'candidates' => ['Tea, brewed', 'Tea']],
    ['key' => 'orange_juice', 'en' => 'Orange juice', 'ro' => 'Suc de portocale', 'candidates' => ['Orange juice', 'Juice, orange']],
    ['key' => 'beer', 'en' => 'Beer', 'ro' => 'Bere', 'candidates' => ['Beer, lager', 'Beer']],
    ['key' => 'wine', 'en' => 'Wine', 'ro' => 'Vin', 'candidates' => ['Wine, red', 'Wine']],
];
